### ISSUE TITLE
Crashing after latest update

### ISSUE THREAD

**Issue by JohnnyBlazzed** [F4ndroid/FrenchToast#1]
After the latest update (0.2.6) I, and a couple of my friends, crash before the loading screen. Not sure what part of the log to copy but here is the last bit of it.
Description: There was a severe problem during mod loading that has caused the game to fail
[17/10/2016 00:16:01 AM] 
[17/10/2016 00:16:01 AM] net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/bdew/pressure/blocks/tank/blocks/DataPortCommands$
[17/10/2016 00:16:01 AM]    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
[17/10/2016 00:16:01 AM]    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:792)
[17/10/2016 00:16:01 AM]    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324)
[17/10/2016 00:16:01 AM]    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
[17/10/2016 00:16:01 AM]    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
[17/10/2016 00:16:01 AM]    at net.minecraft.client.main.Main.main(SourceFile:124)
[17/10/2016 00:16:01 AM]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17/10/2016 00:16:01 AM]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17/10/2016 00:16:01 AM]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17/10/2016 00:16:01 AM]    at java.lang.reflect.Method.invoke(Unknown Source)
[17/10/2016 00:16:01 AM]    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
[17/10/2016 00:16:01 AM]    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[17/10/2016 00:16:01 AM] Caused by: java.lang.NoClassDefFoundError: net/bdew/pressure/blocks/tank/blocks/DataPortCommands$
[17/10/2016 00:16:01 AM]    at net.bdew.pressure.Pressure$.init(Pressure.scala:69)
[17/10/2016 00:16:01 AM]    at net.bdew.pressure.Pressure.init(Pressure.scala)
[17/10/2016 00:16:01 AM]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17/10/2016 00:16:01 AM]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17/10/2016 00:16:01 AM]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17/10/2016 00:16:01 AM]    at java.lang.reflect.Method.invoke(Unknown Source)
[17/10/2016 00:16:01 AM]    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:597)
[17/10/2016 00:16:01 AM]    at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
[17/10/2016 00:16:01 AM]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17/10/2016 00:16:01 AM]    at java.lang.reflect.Method.invoke(Unknown Source)
[17/10/2016 00:16:01 AM]    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
[17/10/2016 00:16:01 AM]    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
[17/10/2016 00:16:01 AM]    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
[17/10/2016 00:16:01 AM]    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
[17/10/2016 00:16:01 AM]    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
[17/10/2016 00:16:01 AM]    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
[17/10/2016 00:16:01 AM]    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
[17/10/2016 00:16:01 AM]    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17/10/2016 00:16:01 AM]    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17/10/2016 00:16:01 AM]    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17/10/2016 00:16:01 AM]    at java.lang.reflect.Method.invoke(Unknown Source)
[17/10/2016 00:16:01 AM] Checking for updated files!
[17/10/2016 00:16:01 AM] No updates found!

**Comment by F4ndroid** [comment]
Fixed in 0.2.6.1
